theme: jekyll-theme-midnight
title: Dylan Hartley
description: Boise State University Student

<h1> About Me

Hi, my name is Dylan Hartley! I am currently attending Boise State University for a Bachelor's of Science in computer science. 
